module(
    name = "mojito",
    version = "0.1.0",
)

bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "toolchains_llvm", version = "1.7.0")

llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    name = "llvm_toolchain",
    llvm_version = "17.0.6",
    # Global flags for all C/C++ files
    compile_flags = {
        "": [
            "-Wall",
            "-Wextra",
            "-Wpedantic",
            "-Werror",
        ],
    },
    # C++ specific flags
    cxx_flags = {
        "": ["-std=c++20"],
    },
    # Applied only during 'bazel build -c opt'
    opt_compile_flags = {
        "": ["-O3"],
    },
    # Applied only during 'bazel build -c dbg'
    dbg_compile_flags = {
        "": ["-g"],
    },
)

use_repo(llvm, "llvm_toolchain")

register_toolchains("@llvm_toolchain//:all")

bazel_dep(name = "googletest", version = "1.17.0")
